// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFis0XOTvjTuovP8ygQwqILwQIh_MARcY',
    appId: '1:474553393683:web:9783dcb3cb98e49c0755e6',
    messagingSenderId: '474553393683',
    projectId: 'socialmedia-8a568',
    authDomain: 'socialmedia-8a568.firebaseapp.com',
    storageBucket: 'socialmedia-8a568.firebasestorage.app',
    measurementId: 'G-ZTLPXJF5SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaT0rq5ubuzJbdVW1w3b0mikjDqIMXa2c',
    appId: '1:474553393683:android:fc9bac972ae1bc810755e6',
    messagingSenderId: '474553393683',
    projectId: 'socialmedia-8a568',
    storageBucket: 'socialmedia-8a568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQeLaIncHvuKkrnpasnRIEeqdJLMR6Azo',
    appId: '1:474553393683:ios:a89eb5a3c8bf03220755e6',
    messagingSenderId: '474553393683',
    projectId: 'socialmedia-8a568',
    storageBucket: 'socialmedia-8a568.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQeLaIncHvuKkrnpasnRIEeqdJLMR6Azo',
    appId: '1:474553393683:ios:a89eb5a3c8bf03220755e6',
    messagingSenderId: '474553393683',
    projectId: 'socialmedia-8a568',
    storageBucket: 'socialmedia-8a568.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFis0XOTvjTuovP8ygQwqILwQIh_MARcY',
    appId: '1:474553393683:web:12b64ddeb9888ee00755e6',
    messagingSenderId: '474553393683',
    projectId: 'socialmedia-8a568',
    authDomain: 'socialmedia-8a568.firebaseapp.com',
    storageBucket: 'socialmedia-8a568.firebasestorage.app',
    measurementId: 'G-NR00C6XWVH',
  );
}
